Reformat order controllers
AY2122S2-CS2113-T11-4/tp pull request #36
Opened 2022-03-14 07:50 UTC by z0723-julie

2022-03-14 07:59 UTC, darylhjd requested changes
Make each choice its own method. Also, use `InputParser` methods for getting input, no need to write your own.

2022-03-15 04:02 UTC, darylhjd approved these changes

2022-03-15 04:03 UTC, merged

2022-03-15 04:10 UTC, BotBw commented on src/main/java/seedu/duke/controllers/OrderController.java
> +    protected boolean optionSwitcher(int choice) throws IllegalArgumentException, OperationTerminationException {
Only `OperationTerminationException` here

2022-03-15 04:10 UTC, BotBw commented on src/main/java/seedu/duke/controllers/OrderController.java
>          case 0:
return true here?

2022-03-15 04:10 UTC, BotBw commented on src/main/java/seedu/duke/controllers/OrderController.java
> +    private void quitOrder() throws OperationTerminationException {
this should be something like `addMultipleDish`?